{ pkgs, ... }:
{
  # Generated by `nixos-generate-config --root /mnt` during install — copy
  # the result here (see PARTITION-RUNBOOK.md step 9) before `nixos-install`.
  imports = [ ./hardware-configuration.nix ];

  nixpkgs.config.allowUnfree = true; # vivaldi, vscode, claude-code
  # noctalia-shell.overlays.default was tried and reverted: an overlay
  # builds against THIS nixpkgs, and the meson build wanted a
  # wayland-protocols staging file this pin didn't have.
  # noctalia-shell.nixosModules.default (imported in flake.nix) already
  # sets programs.noctalia.package to the flake's own package output.
  #
  # Ubuntu starts noctalia via ~/.local/share/systemd/user/noctalia.service
  # (ExecStart=/usr/local/bin/noctalia) which lives in the shared home, so
  # NixOS sees the unit — but /usr/local/bin/noctalia is Ubuntu-only, so
  # the unit fails. Putting the binary in home.packages does not help:
  # nothing execs that store path. This NixOS user unit lives in
  # /etc/systemd/user, which outranks ~/.local/share, so the same unit
  # *name* (and the shared enable symlink under
  # graphical-session.target.wants) runs the store path instead.
  # Do NOT use the home-manager module for this: it would write the unit
  # into ~/.config/systemd/user and collide with the shared home, same
  # class of failure as the mouseless.service abort.
  programs.noctalia = {
    enable = true;
    systemd.enable = true;
    recommendedServices.enable = true; # bluetooth, upower, power-profiles-daemon
  };

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot"; # matches both the internal-disk
    # ESP (nvme0n1p6, mounted at /boot per PARTITION-RUNBOOK.md step 8) and
    # disko-usb.nix's ESP mountpoint.
  # NixOS's OWN ESP — never touches Ubuntu's ESP or GRUB. Switch OS via the
  # firmware boot menu (F9).

  # Per-host: networking.hostName, GPU driver, and the /mnt/ubuntu +
  # /home/erik share (each machine's Ubuntu partition has a different UUID —
  # see hosts/hp-envy.nix and hosts/nitro.nix). Both use `nofail` on the
  # mount/bind so a config accidentally built for the wrong host degrades to
  # a normal empty local home instead of a broken boot.

  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Stockholm"; # adjust if wrong
  i18n.defaultLocale = "en_US.UTF-8";

  # uid AND gid both have to match Ubuntu's erik (1000:1000), not just the
  # uid: the home directory is shared between the two systems, so files
  # created from NixOS would otherwise land with group 100 ("users", the
  # NixOS default) against Ubuntu's 1000. The missing `erik` group also
  # broke systemd-tmpfiles on the first boot — the /dev/uinput rules below
  # name it: "Failed to resolve group 'erik': No such process".
  users.groups.erik.gid = 1000;
  users.users.erik = {
    isNormalUser = true;
    uid = 1000;
    group = "erik";
    extraGroups = [ "wheel" "networkmanager" "video" "input" ];
    shell = pkgs.bash;
  };

  hardware.graphics.enable = true; # GPU-specific extras (nvidia, intel-media-driver) are per-host

  # nixpkgs' own programs.niri.enable (not niri-flake). niri-flake forced a
  # from-source Rust build that hit a crates.io 403; this pin ships niri
  # 26.04 as a cached binary AND, via systemd.packages, installs its user
  # units (niri.service, niri-shutdown.target). Without those units,
  # niri-session cannot start niri.service, graphical-session.target never
  # becomes active, and every WantedBy=graphical-session.target user unit
  # in the shared home stays dead — including Ubuntu's noctalia.service
  # and mouseless.service. greetd must exec niri-session, not the bare
  # niri binary, for the same reason.
  programs.niri = {
    enable = true;
    useNautilus = false; # gtk file-chooser is enough; nautilus is a big extra
  };

  services.greetd = {
    enable = true;
    settings.default_session = {
      # pkgs.tuigreet, not pkgs.greetd.tuigreet -- it moved out of the greetd
      # attribute set into a top-level package in newer nixpkgs.
      command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --cmd ${pkgs.niri}/bin/niri-session";
      user = "greeter";
    };
  };

  security.polkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true; # steam
    pulse.enable = true;
  };
  services.pulseaudio.enable = false; # was hardware.pulseaudio, renamed on this nixpkgs revision

  # mouseless (net.sonuscape.mouseless) is flatpak-installed on the Ubuntu
  # side. Enable flatpak here, then after first boot:
  #   flatpak remote-list          # check the Ubuntu install for which remote it came from
  #   flatpak install <remote> net.sonuscape.mouseless
  services.flatpak.enable = true;
  xdg.portal = {
    enable = true; # required assertion for flatpak; niri itself also needs a portal for screen-share/file-pickers
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ]; # generic backend, not niri-specific — good enough for a smoke test
  };

  programs.steam.enable = true;
  # gamescopeSession dropped along with the rest of the trimmed app set --
  # erik only asked for plain steam back, not gamescope.

  # niri ships no Xwayland of its own, so in a bare niri session DISPLAY is
  # unset and every X11-only app dies -- steam pops "Unable to open a
  # connection to X". xwayland-satellite supplies the X server. The display
  # number is pinned to :0 so niri's environment block (shared home,
  # ~/.config/niri/config.kdl) can hand the same DISPLAY to the clients niri
  # spawns; those inherit niri's env and would otherwise miss the DISPLAY
  # that xwayland-satellite pushes into the systemd/dbus activation env.
  systemd.user.services.xwayland-satellite = {
    description = "Xwayland outside your Wayland";
    bindsTo = [ "graphical-session.target" ];
    partOf = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    requisite = [ "graphical-session.target" ];
    wantedBy = [ "graphical-session.target" ];
    serviceConfig = {
      Type = "notify";
      NotifyAccess = "all";
      ExecStart = "${pkgs.xwayland-satellite}/bin/xwayland-satellite :0";
      StandardOutput = "journal";
    };
  };

  # nix-ld gör att NixOS kan köra vanliga dynamiskt länkade Linux-binärer
  programs.nix-ld.enable = true;

  # Mouseless virtual-mouse/device quirks, ported verbatim from this Ubuntu
  # install's /etc/udev/rules.d/61-mouseless-no-takeover.rules and
  # /etc/tmpfiles.d/mouseless-input.conf.
  services.udev.extraRules = ''
    ACTION=="add|change", SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="Mouseless-Virtual-Mouse", ENV{ID_INPUT_JOYSTICK}="0", ENV{ID_INPUT_MOUSE}="1"
    ACTION=="add|change", SUBSYSTEM=="input", KERNEL=="js*", ATTRS{name}=="Mouseless-Virtual-Mouse", MODE="0000", GROUP="root"
    ACTION=="add|change", SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="*Controller Touchpad*", ENV{LIBINPUT_IGNORE_DEVICE}="1", ENV{ID_INPUT_MOUSE}="0", ENV{ID_INPUT_TOUCHPAD}="0"
  '';
  systemd.tmpfiles.rules = [
    "z /dev/uinput       0660 erik erik - -"
    "z /dev/input/event* 0660 erik erik - -"
  ];

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  system.stateVersion = "25.05"; # matches the nixpkgs/home-manager release-25.05 pin
}
