{ pkgs, noctalia-shell, ... }:
{
  # Generated by `nixos-generate-config --root /mnt` during install — copy
  # the result here (see PARTITION-RUNBOOK.md step 9) before `nixos-install`.
  imports = [ ./hardware-configuration.nix ];

  nixpkgs.config.allowUnfree = true; # vivaldi, discord, spotify, steam, vscode
  nixpkgs.overlays = [ noctalia-shell.overlays.default ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot"; # matches both the internal-disk
    # ESP (nvme0n1p6, mounted at /boot per PARTITION-RUNBOOK.md step 8) and
    # disko-usb.nix's ESP mountpoint.
  # NixOS's OWN ESP — never touches Ubuntu's ESP or GRUB. Switch OS via the
  # firmware boot menu (F9).

  # Per-host: networking.hostName, GPU driver, and the /mnt/ubuntu +
  # /home/erik share (each machine's Ubuntu partition has a different UUID —
  # see hosts/hp-envy.nix and hosts/nitro.nix). Both use `nofail` on the
  # mount/bind so a config accidentally built for the wrong host degrades to
  # a normal empty local home instead of a broken boot.

  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Stockholm"; # adjust if wrong
  i18n.defaultLocale = "en_US.UTF-8";

  users.users.erik = {
    isNormalUser = true;
    uid = 1000; # matches Ubuntu's erik (confirmed 2026-09-03) — same numeric
      # owner on files under the shared /mnt/ubuntu mount either way
    extraGroups = [ "wheel" "networkmanager" "video" "input" ];
    shell = pkgs.bash;
  };

  hardware.graphics.enable = true; # GPU-specific extras (nvidia, intel-media-driver) are per-host

  # From niri-flake's NixOS module. Confirm attribute surface with
  # `nix flake show github:sodiboo/niri-flake` once online — unverified from
  # this machine (no nix installed here).
  programs.niri.enable = true;

  services.greetd = {
    enable = true;
    settings.default_session = {
      command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --remember --cmd niri-session";
      user = "greeter";
    };
  };

  security.polkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true; # steam
    pulse.enable = true;
  };
  hardware.pulseaudio.enable = false;

  # mouseless (net.sonuscape.mouseless) is flatpak-installed on the Ubuntu
  # side. Enable flatpak here, then after first boot:
  #   flatpak remote-list          # check the Ubuntu install for which remote it came from
  #   flatpak install <remote> net.sonuscape.mouseless
  services.flatpak.enable = true;

  programs.steam = {
    enable = true;
    gamescopeSession.enable = true; # niri config.kdl has a window-rule matching app-id="^gamescope"
  };

  # Mouseless virtual-mouse/device quirks, ported verbatim from this Ubuntu
  # install's /etc/udev/rules.d/61-mouseless-no-takeover.rules and
  # /etc/tmpfiles.d/mouseless-input.conf.
  services.udev.extraRules = ''
    ACTION=="add|change", SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="Mouseless-Virtual-Mouse", ENV{ID_INPUT_JOYSTICK}="0", ENV{ID_INPUT_MOUSE}="1"
    ACTION=="add|change", SUBSYSTEM=="input", KERNEL=="js*", ATTRS{name}=="Mouseless-Virtual-Mouse", MODE="0000", GROUP="root"
    ACTION=="add|change", SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="*Controller Touchpad*", ENV{LIBINPUT_IGNORE_DEVICE}="1", ENV{ID_INPUT_MOUSE}="0", ENV{ID_INPUT_TOUCHPAD}="0"
  '';
  systemd.tmpfiles.rules = [
    "z /dev/uinput       0660 erik erik - -"
    "z /dev/input/event* 0660 erik erik - -"
  ];

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Match whatever release the installer ISO actually is at install time.
  system.stateVersion = "25.11";
}
