{
  description = "erik's niri evaluation NixOS config (dual-boot alongside Ubuntu, own partition/ESP)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # Tracks upstream niri releases closely; provides the NixOS + home-manager
    # modules. Confirm this is still the right choice once nixpkgs' own
    # niri module is reachable (`nix search nixpkgs niri`) — may be redundant
    # by install time.
    niri = {
      url = "github:sodiboo/niri-flake";
      # Without this, niri-flake's own mesa/wayland-stack deps could resolve
      # to a DIFFERENT nixpkgs revision than everything else here, and Nix
      # would store two non-identical copies instead of deduplicating one —
      # this is what actually makes packages NOT share a library in Nix.
      inputs.nixpkgs.follows = "nixpkgs";
    };
    noctalia-shell = {
      url = "github:noctalia-dev/noctalia-shell";
      inputs.nixpkgs.follows = "nixpkgs"; # same reasoning — shared Qt6/quickshell stack
    };
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager, niri, noctalia-shell, disko, ... }:
    let
      homeModule = {
        home-manager.useGlobalPackages = true;
        home-manager.useUserPackages = true;
        home-manager.users.erik = import ./home.nix;
      };
    in
    {
      # The real dual-boot install, on its own internal-disk partitions
      # (nvme0n1p6/p7 — see PARTITION-RUNBOOK.md). hardware-configuration.nix
      # generated by `nixos-generate-config --root /mnt` at install time.
      nixosConfigurations.nixos-eval = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit niri noctalia-shell; };
        modules = [
          niri.nixosModules.niri
          ./configuration.nix
          home-manager.nixosModules.home-manager
          homeModule
        ];
      };

      # Smoke-test install target: the 14.6GB external "USB DISK" stick
      # (formerly running Ventoy — see disko-usb.nix), booted from a
      # SEPARATE small USB/SD card flashed with the NixOS installer ISO.
      # Same config as nixos-eval (full app set — this target has the room)
      # minus the internal disk's PARTITION-RUNBOOK.md; disko partitions it
      # instead. hardware-configuration.nix gets regenerated/overwritten for
      # whichever target you're installing at the time — this repo isn't set
      # up to keep both targets' hardware configs simultaneously.
      nixosConfigurations.nixos-eval-usb = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit niri noctalia-shell; };
        modules = [
          niri.nixosModules.niri
          disko.nixosModules.disko
          ./disko-usb.nix
          ./configuration.nix
          home-manager.nixosModules.home-manager
          homeModule
        ];
      };
    };
}
