config_version = 14

[backdrop]
blur_intensity = 0.25999999418854713
enabled = true
tint_intensity = 0.669999985024333

[bar.default]
center = [ "clock", "date", "spacer_2", "cpu", "network_rx", "ram", "temp", "weather" ]
start = [
    "launcher",
    "wallpaper",
    "workspaces",
    "active_window",
    "audio_visualizer",
    "cat",
    "launcher_2",
    "pulse",
    "widget",
    "nix-monitor",
    "status"
]

[calendar]
enabled = true

[control_center.calendar]
show_week_numbers = true

[desktop_widgets]
enabled = true
schema_version = 2
widget_order = [
    "sysmon-cpu@DP-2",
    "sysmon-ram@DP-2",
    "sysmon-gpu@DP-2",
    "sysmon-vram@DP-2",
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004"
]

    [desktop_widgets.grid]
    cell_size = 32
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 125.17578125
    box_width = 141.26171875
    cx = 102.630859375
    cy = 1507.205078125
    output = "DP-1"
    placement_height = 2048.0
    placement_width = 1152.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background_padding = 0
        display = "graph"
        stat = "cpu_usage"
        stat2 = "gpu_usage"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 125.17577362060547
    box_width = 141.26171875
    cx = 102.630859375
    cy = 1649.0709228515625
    output = "DP-1"
    placement_height = 2048.0
    placement_width = 1152.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = true
        background_padding = 0
        display = "graph"
        gauge_layout = "vertical"
        stat = "cpu_temp"
        stat2 = "gpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 125.17577362060547
    box_width = 141.26171875
    cx = 102.630859375
    cy = 1796.500244140625
    output = "DP-1"
    placement_height = 2048.0
    placement_width = 1152.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background_padding = 0
        display = "graph"
        stat = "ram_pct"
        stat2 = "gpu_vram_used"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 125.17577362060547
    box_width = 141.26171875
    cx = 102.630859375
    cy = 1950.587890625
    output = "DP-1"
    placement_height = 2048.0
    placement_width = 1152.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background_padding = 0
        display = "graph"
        network_speed_compact = true
        stat = "net_tx"
        stat2 = "net_rx"

    [desktop_widgets.widget."sysmon-cpu@DP-2"]
    box_height = 125.17578125
    box_width = 141.26171875
    cx = 2966.017578125
    cy = 115.205078125
    output = "DP-2"
    placement_height = 1728.0
    placement_width = 3072.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget."sysmon-cpu@DP-2".settings]
        background_opacity = 0.80000000000000004
        background_padding = 0
        display = "graph"
        stat = "cpu_usage"
        stat2 = "gpu_usage"

    [desktop_widgets.widget."sysmon-gpu@DP-2"]
    box_height = 125.17577362060547
    box_width = 141.26171875
    cx = 2966.017578125
    cy = 404.50021362304688
    output = "DP-2"
    placement_height = 1728.0
    placement_width = 3072.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget."sysmon-gpu@DP-2".settings]
        background_padding = 0
        display = "graph"
        stat = "ram_pct"
        stat2 = "gpu_vram_used"

    [desktop_widgets.widget."sysmon-ram@DP-2"]
    box_height = 125.17577362060547
    box_width = 141.26171875
    cx = 2966.017578125
    cy = 257.07095336914062
    output = "DP-2"
    placement_height = 1728.0
    placement_width = 3072.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget."sysmon-ram@DP-2".settings]
        background = true
        background_padding = 0
        display = "graph"
        gauge_layout = "vertical"
        stat = "cpu_temp"
        stat2 = "gpu_temp"

    [desktop_widgets.widget."sysmon-vram@DP-2"]
    box_height = 125.17577362060547
    box_width = 141.26171875
    cx = 2966.017578125
    cy = 558.587890625
    output = "DP-2"
    placement_height = 1728.0
    placement_width = 3072.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget."sysmon-vram@DP-2".settings]
        background_padding = 0
        display = "graph"
        network_speed_compact = true
        stat = "net_tx"
        stat2 = "net_rx"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 9000.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@DP-2", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 576.0
    cy = 1866.0
    output = "DP-1"
    placement_height = 2048.0
    placement_width = 1152.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1536.0
    cy = 1546.0
    output = "DP-2"
    placement_height = 1728.0
    placement_width = 3072.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1536.0
    cy = 1546.0
    output = "HDMI-A-1"
    placement_height = 1728.0
    placement_width = 3072.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]
enabled = [
    "noctalia/bongocat",
    "alexander/game-launcher",
    "lowcache/claude-companion",
    "yocraft/desktop-launcher",
    "tphilippot/git_companion",
    "avivbintangaringga/nix-monitor",
    "tordex/nvtop",
    "davemhammer/tailscale",
    "dunarand/tmux-provider"
]

[shell]
lang = "sv"
screen_time_enabled = true

    [shell.animation]
    speed = 2.0000000298023224

    [shell.panel]
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    directory = "/home/erik/Pictures/Screenshots"

    [shell.shadow]
    alpha = 0.79999998211860657
    direction = "down_left"

[theme]
builtin = "Noctalia"
community_palette = "Shien"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "kcolorscheme", "niri", "qt" ]
    community_ids = [ "claude-code", "vscode", "lazygit" ]

[wallpaper]
fill_mode = "center"

    [wallpaper.default]
    path = "/home/erik/Pictures/hyperlink-dimension-al-7680x4320.jpg"

    [wallpaper.last]
    path = "/home/erik/Pictures/hyperlink-dimension-al-7680x4320.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/erik/Pictures/hyperlink-dimension-al-7680x4320.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/erik/Pictures/hyperlink-dimension-al-7680x4320.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/erik/Pictures/hyperlink-dimension-al-7680x4320.jpg"

[widget.cat]
audio_spectrum = true
rave_mode = true
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.launcher_2]
capsule = true
type = "alexander/game-launcher:launcher"

[widget.nix-monitor]
type = "avivbintangaringga/nix-monitor:nix-monitor"

[widget.pulse]
type = "lowcache/claude-companion:pulse"

[widget.spacer_2]
type = "spacer"

[widget.status]
type = "davemhammer/tailscale:status"

[widget.widget]
type = "tphilippot/git_companion:widget"
