{ pkgs, ... }:
{
  # Generated by `nixos-generate-config --no-filesystems --root /mnt` during
  # install (disko already supplies the filesystems from disko-nitro.nix) --
  # copy the result to ../hardware-configuration-nitro.nix before
  # `nixos-install`. Its own file, not the shared name hp-envy used to
  # import from configuration.nix: two hosts can't share one
  # hardware-configuration.nix without one's `nixos-generate-config`
  # silently overwriting the other's UUIDs.
  imports = [ ../hardware-configuration-nitro.nix ];

  networking.hostName = "nixos-nitro";

  # Intel Arc A750 (DG2, discrete) — confirmed via lspci over SSH, 2026-09-03.
  # No nvidia.* needed; Mesa's iris/anv drivers handle it through the
  # `hardware.graphics.enable` already set in configuration.nix. Adding the
  # media driver for hardware video decode/encode, standard recommendation
  # for modern Intel GPUs (both iHD and legacy i965 variants, harmless to
  # include both).
  hardware.graphics.extraPackages = with pkgs; [ intel-media-driver intel-vaapi-driver ];

  # Whole-disk install (2026-09-07) — Ubuntu is gone, disko-nitro.nix
  # partitions the entire nvme0n1 for NixOS alone. No /mnt/ubuntu, no bind
  # mount: unlike hp-envy's history, this /home was never shared with
  # another OS, so there is no inherited layout to work around.

  # 20G swapfile on its own nodatacow @swap subvolume (disko-nitro.nix) --
  # 31G RAM was not enough headroom during the very first build (tmpfs
  # root filled up mid-build, see NITRO-INSTALL-RUNBOOK.md), so give the
  # installed system real swap rather than relying on RAM alone for large
  # rebuilds.
  swapDevices = [{
    device = "/swap/swapfile";
    size = 20 * 1024;
  }];

  # AngelBeach's self-hosted CI runner — same story as hosts/hp-envy.nix's
  # copy of this block: nitro used to run the runner as an Ubuntu
  # `actions.runner.*.service` against `~/actions-runner`; today's whole-disk
  # NixOS reinstall (see the swap comment above) took that OS, and with it
  # the service, with it. `replace = true` reclaims the existing (now
  # offline) GitHub Actions runner entry rather than leaving a dead
  # duplicate. See hosts/hp-envy.nix for the tokenFile setup steps.
  #
  # serviceOverrides.ProtectHome = false for the same reason as hp-envy.nix:
  # the module's default hardening hides all of /home, which breaks
  # build-linux.yml's lookup of `$HOME/UnrealEngine-Angelscript` and (if a
  # workDir is ever pointed under /home here too) the CHDIR into it — see
  # the hp-envy.nix comment for the exact failure this caused there
  # (2026-09-07).
  services.github-runners.angelbeach-ue5 = {
    enable = true;
    url = "https://github.com/nergnezor/AngelBeach";
    name = "erik-Nitro-N50-640";
    tokenFile = "/etc/github-runner-token";
    replace = true;
    extraLabels = [ "ue5" ];
    user = "erik";
    serviceOverrides.ProtectHome = false;
    # actions/checkout runs with lfs:true; the service's PATH (built from
    # this list, not the interactive shell's) otherwise has no git-lfs.
    extraPackages = [ pkgs.git-lfs ];
  };
}
