{ pkgs, ... }:
{
  # Generated by `nixos-generate-config --no-filesystems --root /mnt` during
  # install (disko already supplies the filesystems from disko-nitro.nix) --
  # copy the result to ../hardware-configuration-nitro.nix before
  # `nixos-install`. Its own file, not the shared name hp-envy used to
  # import from configuration.nix: two hosts can't share one
  # hardware-configuration.nix without one's `nixos-generate-config`
  # silently overwriting the other's UUIDs.
  imports = [ ../hardware-configuration-nitro.nix ];

  networking.hostName = "nixos-nitro";

  # Intel Arc A750 (DG2, discrete) — confirmed via lspci over SSH, 2026-09-03.
  # No nvidia.* needed; Mesa's iris/anv drivers handle it through the
  # `hardware.graphics.enable` already set in configuration.nix. Adding the
  # media driver for hardware video decode/encode, standard recommendation
  # for modern Intel GPUs (both iHD and legacy i965 variants, harmless to
  # include both).
  hardware.graphics.extraPackages = with pkgs; [ intel-media-driver intel-vaapi-driver ];

  # Whole-disk install (2026-09-07) — Ubuntu is gone, disko-nitro.nix
  # partitions the entire nvme0n1 for NixOS alone. No /mnt/ubuntu, no bind
  # mount: unlike hp-envy's history, this /home was never shared with
  # another OS, so there is no inherited layout to work around.

  # 20G swapfile on its own nodatacow @swap subvolume (disko-nitro.nix) --
  # 31G RAM was not enough headroom during the very first build (tmpfs
  # root filled up mid-build, see NITRO-INSTALL-RUNBOOK.md), so give the
  # installed system real swap rather than relying on RAM alone for large
  # rebuilds.
  swapDevices = [{
    device = "/swap/swapfile";
    size = 20 * 1024;
  }];
}
